// Command neongen emits the arm64 NEON/SHA3 kernels, the eight-message kernels,
// and the portable unrolled fixed-32-byte compressor. It is the source of truth
// for all of those outputs.
//
// The kernel hashes four independent 32-byte messages per iteration. The four
// messages are loaded and transposed so that vector lane k of register Vw holds
// message word w of message k; the two RIPEMD-160 pipelines then run with one
// 32-bit lane per message. Constants live in registers for the whole call, each
// round's additive constant is materialized once per round (not per step), and
// the all-zero schedule words of the single-block padding are skipped entirely.
//
// Register allocation:
//
//	V0..V7   message schedule words x0..x7 (reloaded and transposed per block)
//	V8       0x00000080 (schedule word x8, the padding "1" bit)
//	V9       current round's left additive constant
//	V10      current round's right additive constant
//	V14      0x00000100 (schedule word x14, the 256-bit message length)
//	V31      0xffffffff (mask for the bitwise-NOT in f3/f5)
//	V16..V30 the two pipelines' state plus the per-step scratch (rotation pool)
//	V0..V4   reused for the finalized digest words after the rounds complete
//
// The generator is the single source of truth for block_arm64.s,
// block_sha3_arm64.s, block8_arm64.s and block8_sha3_arm64.s; do not edit the
// assembly by hand (see CONTRIBUTING.md).
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// modulePath is the import path of the module that owns the generated file. It
// is used to verify the resolved repository root before writing, so a wrong
// working directory fails loudly instead of silently writing outside the repo.
const modulePath = "github.com/Asylian21/ripemd160-asm"

var rl = [80]int{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	7, 4, 13, 1, 10, 6, 15, 3, 12, 0, 9, 5, 2, 14, 11, 8,
	3, 10, 14, 4, 9, 15, 8, 1, 2, 7, 0, 6, 13, 11, 5, 12,
	1, 9, 11, 10, 0, 8, 12, 4, 13, 3, 7, 15, 14, 5, 6, 2,
	4, 0, 5, 9, 7, 12, 2, 10, 14, 1, 3, 8, 11, 6, 15, 13,
}

var rr = [80]int{
	5, 14, 7, 0, 9, 2, 11, 4, 13, 6, 15, 8, 1, 10, 3, 12,
	6, 11, 3, 7, 0, 13, 5, 10, 14, 15, 8, 12, 4, 9, 1, 2,
	15, 5, 1, 3, 7, 14, 6, 9, 11, 8, 12, 2, 10, 0, 4, 13,
	8, 6, 4, 1, 3, 11, 15, 0, 5, 12, 2, 13, 9, 7, 10, 14,
	12, 15, 10, 4, 1, 5, 8, 7, 6, 2, 13, 14, 0, 3, 9, 11,
}

var sl = [80]int{
	11, 14, 15, 12, 5, 8, 7, 9, 11, 13, 14, 15, 6, 7, 9, 8,
	7, 6, 8, 13, 11, 9, 7, 15, 7, 12, 15, 9, 11, 7, 13, 12,
	11, 13, 6, 7, 14, 9, 13, 15, 14, 8, 13, 6, 5, 12, 7, 5,
	11, 12, 14, 15, 14, 15, 9, 8, 9, 14, 5, 6, 8, 6, 5, 12,
	9, 15, 5, 11, 6, 8, 13, 12, 5, 12, 13, 14, 11, 8, 5, 6,
}

var sr = [80]int{
	8, 9, 9, 11, 13, 15, 15, 5, 7, 7, 8, 11, 14, 14, 12, 6,
	9, 13, 15, 7, 12, 8, 9, 11, 7, 7, 12, 7, 6, 15, 13, 11,
	9, 7, 15, 11, 8, 6, 6, 14, 12, 13, 5, 14, 13, 13, 7, 5,
	15, 5, 8, 11, 14, 14, 6, 14, 6, 9, 12, 9, 12, 5, 15, 8,
	8, 5, 12, 9, 12, 5, 14, 6, 8, 13, 6, 5, 15, 13, 11, 11,
}

// iv is the RIPEMD-160 initial chaining value, broadcast into both pipelines at
// the start of each block and added back during finalization.
var iv = [5]uint32{0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476, 0xc3d2e1f0}

// leftK and rightK are the additive round constants, indexed by round (j/16).
// The unused entries are zero: the left pipeline adds nothing in round 0 and the
// right pipeline adds nothing in round 4, matching the scalar reference.
var leftK = [5]uint32{0, 0x5a827999, 0x6ed9eba1, 0x8f1bbcdc, 0xa953fd4e}
var rightK = [5]uint32{0x50a28be6, 0x5c4dd124, 0x6d703ef3, 0x7a6d76e9, 0}

// Fixed register assignments held live for the whole call.
const (
	regX8   = 8  // schedule word x8  = 0x80
	regLK   = 9  // current round's left additive constant
	regRK   = 10 // current round's right additive constant
	regX14  = 14 // schedule word x14 = 256
	regOnes = 31 // 0xffffffff, for the bitwise-NOT in f3/f5
)

func main() {
	root := repoRoot()
	write(filepath.Join(root, "block_arm64.s"), kernel(false))
	write(filepath.Join(root, "block_sha3_arm64.s"), kernel(true))
	write(filepath.Join(root, "block8_arm64.s"), kernel8(false))
	write(filepath.Join(root, "block8_sha3_arm64.s"), kernel8(true))
	write(filepath.Join(root, "scalar32_generated.go"), scalar32())
}

func kernel(sha3 bool) []byte {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	name := "hash32NEON"
	if sha3 {
		name += "SHA3"
	}

	p("// Code generated by internal/neongen; DO NOT EDIT.")
	p("//go:build arm64")
	p("")
	p("#include \"textflag.h\"")
	p("")
	p("// func %s(dst, src []byte, n int)", name)
	p("//")
	p("// Hashes four 32-byte messages per loop iteration. The caller guarantees n")
	p("// is a positive multiple of four; the scalar tail is handled in Go.")
	p("TEXT ·%s(SB), NOSPLIT, $0-56", name)
	p("\tMOVD\tdst_base+0(FP), R0")
	p("\tMOVD\tsrc_base+24(FP), R1")
	p("\tMOVD\tn+48(FP), R2")
	p("\tCBZ\tR2, done")
	p("")
	p("\t// Call-invariant constants.")
	bcast(&b, 0x80, regX8)
	bcast(&b, 0x100, regX14)
	if !sha3 {
		bcast(&b, 0xffffffff, regOnes)
	}
	p("")
	p("loop:")
	transpose(&b)

	leftState := [5]int{16, 17, 18, 19, 20}
	rightState := [5]int{21, 22, 23, 24, 25}
	p("\t// Broadcast the initial chaining value into both pipelines.")
	for i, r := range leftState {
		bcast(&b, iv[i], r)
	}
	for i, r := range rightState {
		p("\tVMOV\tV%d.B16, V%d.B16", leftState[i], r)
	}

	for j := 0; j < 80; j++ {
		if j%16 == 0 {
			round := j / 16
			p("\t// round %d additive constants", round)
			if leftK[round] != 0 {
				bcast(&b, roundK(leftK[round], round, sha3), regLK)
			}
			if rightK[round] != 0 {
				bcast(&b, roundK(rightK[round], 4-round, sha3), regRK)
			}
		}
		step(&b, true, j, &leftState, freeReg(leftState, rightState), sha3)
		step(&b, false, j, &rightState, freeReg(leftState, rightState), sha3)
	}

	combine(&b, leftState, rightState)
	store(&b)

	p("\tADD\t$128, R1")
	p("\tSUBS\t$4, R2")
	p("\tBNE\tloop")
	p("done:")
	p("\tRET")

	return []byte(b.String())
}

// For f3 and f5 the SHA3 kernel computes the complemented boolean function t
// with BCAX. Then a + ^t + K is a - t + (K-1), modulo 2^32. Their rounds always
// have a nonzero additive constant, so its adjustment costs no extra step.
func roundK(k uint32, fn int, sha3 bool) uint32 {
	if sha3 && (fn == 2 || fn == 4) {
		return k - 1
	}
	return k
}

// bcast materializes the 32-bit immediate imm into all four lanes of Vdst via a
// scalar load and a DUP (general). The Go assembler's LD1R does not accept a
// memory displacement, so register materialization is used instead of a
// constant pool.
func bcast(b *strings.Builder, imm uint32, dst int) {
	fmt.Fprintf(b, "\tMOVD\t$%#x, R3\n", imm)
	fmt.Fprintf(b, "\tVMOV\tR3, V%d.S4\n", dst)
}

// transpose loads four contiguous 32-byte messages and shuffles them so that
// lane k of Vw holds word w of message k, for w in 0..7.
//
// The messages load as V0=m0[w0..3], V1=m0[w4..7], V2=m1[w0..3], ... V7=m3[w4..7].
// Words 0..3 are a 4x4 transpose of the even registers and words 4..7 of the odd
// registers; the results are gathered back into V0..V7. Scratch uses V16..V27,
// which the pipeline state has not yet claimed at this point.
func transpose(b *strings.Builder) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	p("\t// Load four 32-byte messages.")
	p("\tVLD1\t(R1), [V0.B16]")
	p("\tADD\t$16, R1, R4")
	for i := 1; i <= 7; i++ {
		p("\tVLD1\t(R4), [V%d.B16]", i)
		if i < 7 {
			p("\tADD\t$16, R4, R4")
		}
	}
	p("\t// Transpose words 0..3 (even regs hold m0..m3 words 0..3).")
	transpose4x4(b, 0, 2, 4, 6, 20, 21, 22, 23)
	p("\t// Transpose words 4..7 (odd regs hold m0..m3 words 4..7).")
	transpose4x4(b, 1, 3, 5, 7, 24, 25, 26, 27)
	p("\t// Gather word-major lanes into V0..V7.")
	for i := 0; i <= 7; i++ {
		p("\tVMOV\tV%d.B16, V%d.B16", 20+i, i)
	}
}

// transpose4x4 emits a 4x4 32-bit transpose of (Vp0..Vp3) into (Vq0..Vq3) using
// V16/V17/V18/V19 as scratch. Each input register holds one message's four
// consecutive words; each output register ends up holding one word across the
// four messages (lane = message).
func transpose4x4(b *strings.Builder, p0, p1, p2, p3, q0, q1, q2, q3 int) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	p("\tVZIP1\tV%d.S4, V%d.S4, V16.S4", p1, p0)
	p("\tVZIP2\tV%d.S4, V%d.S4, V17.S4", p1, p0)
	p("\tVZIP1\tV%d.S4, V%d.S4, V18.S4", p3, p2)
	p("\tVZIP2\tV%d.S4, V%d.S4, V19.S4", p3, p2)
	p("\tVZIP1\tV18.D2, V16.D2, V%d.D2", q0)
	p("\tVZIP2\tV18.D2, V16.D2, V%d.D2", q1)
	p("\tVZIP1\tV19.D2, V17.D2, V%d.D2", q2)
	p("\tVZIP2\tV19.D2, V17.D2, V%d.D2", q3)
}

// xreg maps a schedule index to the register that holds it. Indices 9..13 and
// 15 are zero in the single-block padding and contribute nothing, so they are
// reported as skippable.
func xreg(idx int) (reg int, skip bool) {
	switch {
	case idx <= 7:
		return idx, false
	case idx == 8:
		return regX8, false
	case idx == 14:
		return regX14, false
	default:
		return 0, true
	}
}

// step emits one round of one pipeline. st holds the five live state registers
// (a, b, c, d, e); tmp is a scratch register distinct from every live register.
// The state is rotated by renaming registers rather than moving data.
func step(b *strings.Builder, left bool, j int, st *[5]int, tmp int, sha3 bool) {
	a, bb, c, d, e := st[0], st[1], st[2], st[3], st[4]
	var idx, rot, fn, kreg int
	var hasK bool
	if left {
		idx, rot, fn = rl[j], sl[j], j/16
		kreg, hasK = regLK, leftK[j/16] != 0
	} else {
		idx, rot, fn = rr[j], sr[j], 4-j/16
		kreg, hasK = regRK, rightK[j/16] != 0
	}

	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	p("\t// %s step %d", side(left), j)
	// The a + message + K terms are independent of f(B,C,D). Forming them
	// first lets the CPU overlap these additions with the boolean function,
	// instead of appending every add to the function's dependency chain.
	if xr, skip := xreg(idx); !skip {
		p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", xr, a, a)
	}
	if hasK {
		p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", kreg, a, a)
	}
	emitF(b, fn, bb, c, d, tmp, sha3, regOnes)
	if sha3 && (fn == 2 || fn == 4) {
		p("\tVSUB\tV%d.S4, V%d.S4, V%d.S4", tmp, a, tmp)
	} else {
		p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", a, tmp, tmp)
	}
	rotl(b, tmp, a, rot)
	p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", e, a, a)
	rotl(b, c, tmp, 10)
	*st = [5]int{e, a, bb, tmp, d}
}

// emitF writes f_fn(B, C, D) into Vout for round fn (0..4) of either pipeline.
// ones is the all-ones register used by the base NEON boolean forms; the SHA3
// forms do not read it.
func emitF(b *strings.Builder, fn, bb, c, d, out int, sha3 bool, ones int) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	if sha3 {
		switch fn {
		case 0:
			p("\tVEOR3\tV%d.B16, V%d.B16, V%d.B16, V%d.B16", d, c, bb, out)
			return
		case 2: // ~f3 = D ^ (C & ~B); step subtracts it using K-1.
			p("\tVBCAX\tV%d.B16, V%d.B16, V%d.B16, V%d.B16", bb, c, d, out)
			return
		case 4: // ~f5 = B ^ (D & ~C); step subtracts it using K-1.
			p("\tVBCAX\tV%d.B16, V%d.B16, V%d.B16, V%d.B16", c, d, bb, out)
			return
		}
	}
	switch fn {
	case 0: // f1 = B ^ C ^ D
		p("\tVEOR\tV%d.B16, V%d.B16, V%d.B16", c, bb, out)
		p("\tVEOR\tV%d.B16, V%d.B16, V%d.B16", d, out, out)
	case 1: // f2 = (B & C) | (~B & D): select C or D using B as the mask.
		p("\tVMOV\tV%d.B16, V%d.B16", bb, out)
		p("\tVBSL\tV%d.B16, V%d.B16, V%d.B16", d, c, out)
	case 2: // f3 = (B | ~C) ^ D
		p("\tVEOR\tV%d.B16, V%d.B16, V%d.B16", ones, c, out)
		p("\tVORR\tV%d.B16, V%d.B16, V%d.B16", out, bb, out)
		p("\tVEOR\tV%d.B16, V%d.B16, V%d.B16", d, out, out)
	case 3: // f4 = (B & D) | (C & ~D): select B or C using D as the mask.
		p("\tVMOV\tV%d.B16, V%d.B16", d, out)
		p("\tVBSL\tV%d.B16, V%d.B16, V%d.B16", c, bb, out)
	case 4: // f5 = B ^ (C | ~D)
		p("\tVEOR\tV%d.B16, V%d.B16, V%d.B16", ones, d, out)
		p("\tVORR\tV%d.B16, V%d.B16, V%d.B16", out, c, out)
		p("\tVEOR\tV%d.B16, V%d.B16, V%d.B16", bb, out, out)
	default:
		panic(fn)
	}
}

// scalar32 emits the fixed-width portable tail. Unrolling turns every rotate
// into an immediate instruction and removes round dispatch and schedule-table
// loads. The arbitrary-length streaming compressor remains independent.
func scalar32() []byte {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	p("// Code generated by internal/neongen; DO NOT EDIT.")
	p("package ripemd160mb")
	p("import (\"encoding/binary\"; \"math/bits\")")
	p("// sum32 hashes exactly one 32-byte message without a schedule loop.")
	p("func sum32(dst, src []byte) {")
	p("_ = src[31]")
	p("_ = dst[19]")
	for i := 0; i < 8; i++ {
		p("x%d := binary.LittleEndian.Uint32(src[%d:%d])", i, i*4, (i+1)*4)
	}
	p("al, bl, cl, dl, el := uint32(init0), uint32(init1), uint32(init2), uint32(init3), uint32(init4)")
	p("ar, br, cr, dr, er := al, bl, cl, dl, el")
	p("var tl, tr uint32")
	word := func(idx int) string {
		switch {
		case idx < 8:
			return fmt.Sprintf("+x%d", idx)
		case idx == 8:
			return "+0x80"
		case idx == 14:
			return "+0x100"
		default:
			return ""
		}
	}
	constant := func(k uint32) string {
		if k == 0 {
			return ""
		}
		return fmt.Sprintf("+%#x", k)
	}
	for j := 0; j < 80; j++ {
		p("tl = bits.RotateLeft32(al+f%d(bl, cl, dl)%s%s, %d)+el", j/16+1, word(rl[j]), constant(leftK[j/16]), sl[j])
		p("al, el, dl, cl, bl = el, dl, bits.RotateLeft32(cl, 10), bl, tl")
		p("tr = bits.RotateLeft32(ar+f%d(br, cr, dr)%s%s, %d)+er", 5-j/16, word(rr[j]), constant(rightK[j/16]), sr[j])
		p("ar, er, dr, cr, br = er, dr, bits.RotateLeft32(cr, 10), br, tr")
	}
	for i, expr := range []string{"init1+cl+dr", "init2+dl+er", "init3+el+ar", "init4+al+br", "init0+bl+cr"} {
		p("binary.LittleEndian.PutUint32(dst[%d:%d], %s)", i*4, (i+1)*4, expr)
	}
	p("}")
	return must(format.Source([]byte(b.String())))
}

// kernel8 emits an eight-message NEON kernel. Each iteration runs two
// independent four-lane groups so the core can overlap four boolean/rotate
// chains instead of the two chains in the four-message kernel. A 512-bit SME
// kernel is faster on one core of this machine but loses once several cores
// share the SME unit, so the wide path stays on per-core NEON.
//
// Register plan (the two message schedules do not fit beside two states):
//
//	V0..V11   group-1 state pool
//	V12       0xffffffff (base kernel only)
//	V13       schedule word x8
//	V14       schedule word x14
//	V15       left round constant
//	V16..V27  group-0 state pool
//	V29       right round constant
//	V30,V31   message word just loaded for group 0 and group 1
//
// Words x0..x7 of both groups are transposed once per iteration into a
// 256-byte stack buffer (word w at [R8+32*w], group 0 then group 1) and
// reloaded on the rounds that use them. x8 and x14 stay in registers.
func kernel8(sha3 bool) []byte {
	const (
		x8r   = 13
		x14r  = 14
		lkR   = 15
		rkR   = 29
		onesR = 12
		wG0   = 30
		wG1   = 31
		g0Lo  = 16
		g0Hi  = 27
		g1Lo  = 0
		g1Hi  = 11
		bufSp = 256 // message buffer bytes; spill follows it
		frame = 512
	)
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	name := "hash32NEON8"
	if sha3 {
		name += "SHA3"
	}

	p("// Code generated by internal/neongen; DO NOT EDIT.")
	p("//go:build arm64")
	p("")
	p("#include \"textflag.h\"")
	p("")
	p("// func %s(dst, src []byte, n int)", name)
	p("//")
	p("// Hashes eight 32-byte messages per loop iteration. The caller guarantees")
	p("// n is a positive multiple of eight; a four-message kernel handles the tail.")
	p("TEXT ·%s(SB), $%d-56", name, frame)
	p("\tMOVD\tdst_base+0(FP), R0")
	p("\tMOVD\tsrc_base+24(FP), R1")
	p("\tMOVD\tn+48(FP), R2")
	p("\tCBZ\tR2, done")
	// msg-frame(SP) is the local buffer. The Go prologue places it 8 bytes above
	// a 16-byte-aligned RSP, so round it up to 32 bytes before the 32-byte
	// word loads. The frame has room for that pad plus the 416 bytes we use.
	p("\tMOVD\t$msg-%d(SP), R8", frame)
	p("\tADD\t$31, R8, R8")
	p("\tBIC\t$31, R8, R8")
	p("")
	p("\t// Call-invariant schedule words. Round constants are refreshed below.")
	bcast(&b, 0x80, x8r)
	bcast(&b, 0x100, x14r)
	if !sha3 {
		bcast(&b, 0xffffffff, onesR)
	}
	p("")
	p("loop:")
	p("\t// Transpose messages 0..3 and 4..7 into the word-major stack buffer.")
	p("\tMOVD\tR1, R6")
	transpose(&b)
	dumpWords(&b, 0)
	p("\tADD\t$128, R6, R1")
	transpose(&b)
	dumpWords(&b, 16)
	p("\tMOVD\tR6, R1")

	left0 := [5]int{16, 17, 18, 19, 20}
	right0 := [5]int{21, 22, 23, 24, 25}
	left1 := [5]int{0, 1, 2, 3, 4}
	right1 := [5]int{5, 6, 7, 8, 9}
	p("\t// Initial chaining value, copied into both groups and both pipelines.")
	for i := range left0 {
		bcast(&b, iv[i], left0[i])
		p("\tVMOV\tV%d.B16, V%d.B16", left0[i], right0[i])
		p("\tVMOV\tV%d.B16, V%d.B16", left0[i], left1[i])
		p("\tVMOV\tV%d.B16, V%d.B16", left0[i], right1[i])
	}

	for j := 0; j < 80; j++ {
		if j%16 == 0 {
			round := j / 16
			p("\t// round %d additive constants", round)
			lk, rk := leftK[round], rightK[round]
			if sha3 {
				if round == 2 || round == 4 {
					lk--
				}
				if 4-round == 2 || 4-round == 4 {
					rk--
				}
			}
			if leftK[round] != 0 {
				bcast(&b, lk, lkR)
			}
			if rightK[round] != 0 {
				bcast(&b, rk, rkR)
			}
		}
		emitWideSide(&b, true, j, &left0, &right0, &left1, &right1, sha3, lkR, rkR, onesR, x8r, x14r)
		emitWideSide(&b, false, j, &left0, &right0, &left1, &right1, sha3, lkR, rkR, onesR, x8r, x14r)
		assertPool(left0, g0Lo, g0Hi)
		assertPool(right0, g0Lo, g0Hi)
		assertPool(left1, g1Lo, g1Hi)
		assertPool(right1, g1Lo, g1Hi)
	}

	p("\t// Park group 1 while group 0 is finalized into V0..V4.")
	spillLive(&b, []int{left1[0], left1[1], left1[2], left1[3], left1[4], right1[0], right1[1], right1[2], right1[3], right1[4]})
	combine(&b, left0, right0)
	store(&b)
	p("\t// Reload group 1 into the register layout combine expects.")
	for i := 0; i < 10; i++ {
		addr(&b, bufSp+i*16, "R3")
		p("\tVLD1\t(R3), [V%d.B16]", 16+i)
	}
	combine(&b, [5]int{16, 17, 18, 19, 20}, [5]int{21, 22, 23, 24, 25})
	store(&b)
	p("")
	p("\tADD\t$256, R1")
	p("\tSUBS\t$8, R2")
	p("\tBNE\tloop")
	p("done:")
	p("\tRET")
	return []byte(b.String())
}

// emitWideSide runs one pipeline side (left or right) for both four-lane groups.
// A message word below x8 is loaded once into V30/V31 and consumed by both groups.
func emitWideSide(b *strings.Builder, left bool, j int, l0, r0, l1, r1 *[5]int, sha3 bool, lkR, rkR, onesR, x8r, x14r int) {
	idx := rr[j]
	// rightK is indexed by the left round (j/16), matching the four-lane kernel.
	// The boolean function on this side is 4-j/16; that index is not the K slot.
	kreg, hasK := rkR, rightK[j/16] != 0
	st0, st1 := r0, r1
	if left {
		idx = rl[j]
		kreg, hasK = lkR, leftK[j/16] != 0
		st0, st1 = l0, l1
	}
	if idx <= 7 {
		addr(b, idx*32, "R3")
		fmt.Fprintf(b, "\tVLD1\t(R3), [V30.B16, V31.B16]\n")
	}
	step8(b, left, j, st0, freeIn(16, 27, *l0, *r0), sha3, word8(idx, 30, x8r, x14r), kreg, hasK, onesR)
	step8(b, left, j, st1, freeIn(0, 11, *l1, *r1), sha3, word8(idx, 31, x8r, x14r), kreg, hasK, onesR)
}

func word8(idx, loaded, x8r, x14r int) int {
	switch {
	case idx <= 7:
		return loaded
	case idx == 8:
		return x8r
	case idx == 14:
		return x14r
	default:
		return -1
	}
}

// step8 is step with the message word and constant register supplied by the
// eight-message scheduler. xReg < 0 means the schedule word is the implicit zero.
func step8(b *strings.Builder, left bool, j int, st *[5]int, tmp int, sha3 bool, xReg, kReg int, hasK bool, ones int) {
	a, bb, c, d, e := st[0], st[1], st[2], st[3], st[4]
	rot, fn := sr[j], 4-j/16
	if left {
		rot, fn = sl[j], j/16
	}
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	p("\t// %s step %d", side(left), j)
	if xReg >= 0 {
		p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", xReg, a, a)
	}
	if hasK {
		p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", kReg, a, a)
	}
	emitF(b, fn, bb, c, d, tmp, sha3, ones)
	if sha3 && (fn == 2 || fn == 4) {
		p("\tVSUB\tV%d.S4, V%d.S4, V%d.S4", tmp, a, tmp)
	} else {
		p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", a, tmp, tmp)
	}
	rotl(b, tmp, a, rot)
	p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", e, a, a)
	rotl(b, c, tmp, 10)
	*st = [5]int{e, a, bb, tmp, d}
}

func dumpWords(b *strings.Builder, hi int) {
	for i := 0; i <= 7; i++ {
		addr(b, i*32+hi, "R3")
		fmt.Fprintf(b, "\tVST1\t[V%d.B16], (R3)\n", i)
	}
}

func spillLive(b *strings.Builder, regs []int) {
	for i, r := range regs {
		addr(b, bufSpill(i), "R3")
		fmt.Fprintf(b, "\tVST1\t[V%d.B16], (R3)\n", r)
	}
}

func bufSpill(i int) int { return 256 + i*16 }

func addr(b *strings.Builder, off int, dst string) {
	if off == 0 {
		fmt.Fprintf(b, "\tMOVD\tR8, %s\n", dst)
		return
	}
	fmt.Fprintf(b, "\tADD\t$%d, R8, %s\n", off, dst)
}

func freeIn(lo, hi int, left, right [5]int) int {
	used := map[int]bool{}
	for _, r := range left {
		used[r] = true
	}
	for _, r := range right {
		used[r] = true
	}
	for r := hi; r >= lo; r-- {
		if !used[r] {
			return r
		}
	}
	panic("neongen: no free vector register in pool")
}

func assertPool(st [5]int, lo, hi int) {
	for _, r := range st {
		if r < lo || r > hi {
			panic(fmt.Sprintf("neongen: register V%d escaped pool %d..%d", r, lo, hi))
		}
	}
}

// rotl writes ROL(Vsrc, n) into Vdst using a shift-left followed by a
// shift-right-and-insert.
func rotl(b *strings.Builder, src, dst, n int) {
	fmt.Fprintf(b, "\tVSHL\t$%d, V%d.S4, V%d.S4\n", n, src, dst)
	fmt.Fprintf(b, "\tVSRI\t$%d, V%d.S4, V%d.S4\n", 32-n, src, dst)
}

// combine performs the RIPEMD-160 finalization, writing the five digest words
// into V0..V4. Those registers held the (now dead) message schedule, so no live
// state register is overwritten before it is read; V5 is the constant scratch.
func combine(b *strings.Builder, l, r [5]int) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	al, bl, cl, dl, el := l[0], l[1], l[2], l[3], l[4]
	ar, br, cr, dr, er := r[0], r[1], r[2], r[3], r[4]
	p("\t// Finalize: digest word w -> V[w]; V5 holds the IV term.")
	emitCombineWord(b, 0, iv[1], cl, dr) // h0 = iv1 + cl + dr
	emitCombineWord(b, 1, iv[2], dl, er) // h1 = iv2 + dl + er
	emitCombineWord(b, 2, iv[3], el, ar) // h2 = iv3 + el + ar
	emitCombineWord(b, 3, iv[4], al, br) // h3 = iv4 + al + br
	emitCombineWord(b, 4, iv[0], bl, cr) // h4 = iv0 + bl + cr
}

func emitCombineWord(b *strings.Builder, out int, ivTerm uint32, left, right int) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	bcast(b, ivTerm, 5)
	p("\tVADD\tV%d.S4, V5.S4, V%d.S4", left, out)
	p("\tVADD\tV%d.S4, V%d.S4, V%d.S4", right, out, out)
}

// store transposes the digest words in V0..V4 back to message-major order and
// writes four contiguous 20-byte digests, advancing R0 by 80 bytes.
//
// V0..V3 hold words 0..3 with one message per lane; a 4x4 transpose gathers each
// message's first four words into one register (V5, V6, V7, V15). Word 4 (V4) is
// stored per lane. All transpose outputs use registers distinct from their
// inputs so nothing is clobbered before it is read.
func store(b *strings.Builder) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	p("\t// Transpose digests back to message-major order and store 4x20 bytes.")
	p("\tVZIP1\tV1.S4, V0.S4, V26.S4")   // [m0w0 m1w0 m0w1 m1w1]
	p("\tVZIP2\tV1.S4, V0.S4, V27.S4")   // [m2w0 m3w0 m2w1 m3w1]
	p("\tVZIP1\tV3.S4, V2.S4, V28.S4")   // [m0w2 m1w2 m0w3 m1w3]
	p("\tVZIP2\tV3.S4, V2.S4, V29.S4")   // [m2w2 m3w2 m2w3 m3w3]
	p("\tVZIP1\tV28.D2, V26.D2, V5.D2")  // message 0: w0 w1 w2 w3
	p("\tVZIP2\tV28.D2, V26.D2, V6.D2")  // message 1: w0 w1 w2 w3
	p("\tVZIP1\tV29.D2, V27.D2, V7.D2")  // message 2: w0 w1 w2 w3
	p("\tVZIP2\tV29.D2, V27.D2, V15.D2") // message 3: w0 w1 w2 w3
	for lane, vreg := range []int{5, 6, 7, 15} {
		p("\tVST1.P\t[V%d.B16], 16(R0)", vreg)
		p("\tVMOV\tV4.S[%d], R3", lane)
		p("\tMOVWU.P\tR3, 4(R0)")
	}
}

// freeReg returns the lowest-numbered scratch register in the rotation pool
// (V16..V30) that is not currently holding pipeline state. The message-word and
// constant registers (V0..V15, V31) are outside this range and never returned.
func freeReg(left, right [5]int) int {
	used := map[int]bool{regOnes: true}
	for _, r := range left {
		used[r] = true
	}
	for _, r := range right {
		used[r] = true
	}
	for r := 26; r <= 30; r++ {
		if !used[r] {
			return r
		}
	}
	for r := 16; r <= 30; r++ {
		if !used[r] {
			return r
		}
	}
	panic("neongen: no free vector register")
}

func side(left bool) string {
	if left {
		return "left"
	}
	return "right"
}

// repoRoot resolves the module root from the generator's working directory and
// verifies it before returning, so an unexpected working directory fails loudly
// instead of writing the generated file somewhere outside the repository.
func repoRoot() string {
	// go:generate runs this as "cd internal/neongen && go run .", so the working
	// directory is <root>/internal/neongen.
	root := filepath.Dir(filepath.Dir(must(os.Getwd())))
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		panic(fmt.Errorf("neongen: cannot read go.mod at resolved root %q: %w", root, err))
	}
	if !bytes.Contains(data, []byte("module "+modulePath)) {
		panic(fmt.Errorf("neongen: resolved root %q is not module %q", root, modulePath))
	}
	return root
}

func must[T any](v T, err error) T {
	if err != nil {
		panic(err)
	}
	return v
}

func write(path string, b []byte) {
	old, _ := os.ReadFile(path)
	if bytes.Equal(old, b) {
		return
	}
	if err := os.WriteFile(path, b, 0o644); err != nil {
		panic(fmt.Errorf("write %s: %w", path, err))
	}
}
